name: FunEffects
main: lostteam\funeffects\Main
author: Lost Team
version: 1.0.0
api: 1.4.0
commands:
   flash:
    description: Gives you speed.
    permission: fe.flash
   sick:
    description: Gives you nausea.
    permission: fe.sick
    heal:
    description: Gives you Instant Health.
    permission: fe.heal
permissions:
  fe:
    default: op
     description: Main permission.
children:
  fe.flash:
    default: op
    description: Flash permission.
  fe.sick:
    default: op
    description: Sick permission.
  fe.heal
    default: op
    description: Heal Permission
