name: FunEffects
main: lostteam\funeffects\Main
author: Lost Team
version: 1.0.0
api: 1.4.0
commands:
   flash:
    description: Gives you speed.
    permission: fe.flash
permissions:
  fe.flash:
    default: op
